spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml      #别名扫描包
  type-aliases-package: com.itheima.mp.domain.po   #Mapper.xml文件地址，默认值
  configuration:
    map-underscore-to-camel-case: true    #是否开启下划线和驼峰的映射
  global-config:
    db-config:
      id-type: auto   #id为自动生成
knife4j:
  enable: true    #开启swagger
  openapi:
    title: 用户接管理
    version: 1.0.0
    concat: 黑马
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.itheima.mp.controller
